# Generated by Django 2.1.4 on 2018-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('icon_name', models.CharField(help_text='Nombre de un fichero .png, .gif o .jpg de 32px de alto, situado en el directorio de iconos', max_length=100, verbose_name='nombre del icono')),
            ],
            options={
                'verbose_name': 'clase de comida',
                'verbose_name_plural': 'clases de comida',
                'ordering': ('name',),
            },
        ),
    ]
