# Generated by Django 2.1.4 on 2018-12-20 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gathering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('slot', models.PositiveSmallIntegerField(choices=[(0, 'Desayuno'), (1, 'Media mañana'), (2, 'Comida'), (3, 'Merienda'), (4, 'Cena')], verbose_name='período')),
            ],
            options={
                'verbose_name': 'comida registrada',
                'verbose_name_plural': 'comidas registradas',
                'ordering': ('user', 'date', 'slot'),
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('nutriscore', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='nutriscore')),
            ],
            options={
                'verbose_name': 'tipo de comida',
                'verbose_name_plural': 'tipos de comida',
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='foodkind',
            options={'ordering': ('name',), 'verbose_name': 'grupo de comida', 'verbose_name_plural': 'grupos de comida'},
        ),
        migrations.AddField(
            model_name='foodtype',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_types', to='gathering.FoodKind', verbose_name='grupo'),
        ),
        migrations.AddField(
            model_name='dayslot',
            name='eaten',
            field=models.ManyToManyField(help_text='Qué tipos de comida has comido en este período', to='gathering.FoodType', verbose_name='comidas'),
        ),
        migrations.AddField(
            model_name='dayslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='dayslot',
            unique_together={('user', 'date', 'slot')},
        ),
    ]
