# Generated by Django 2.1.4 on 2018-12-20 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gathering', '0002_auto_20181220_1015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaySlot',
            new_name='FoodRegistration',
        ),
    ]
